services:
  mariadb:
    image: mariadb:11.4
    container_name: inventario-mariadb
    restart: unless-stopped

    environment:
      MARIADB_DATABASE: inventario_db
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: inventario
      MARIADB_PASSWORD: inventario

    ports:
      - "3306:3306"

    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: