spring.application.name=inventario-backend

spring.datasource.url=jdbc:mariadb://localhost:3306/inventario_db
spring.datasource.username=inventario
spring.datasource.password=inventario
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true